"""Named theme registry for the Claude Usage Widget."""
from __future__ import annotations

_THEMES: dict[str, dict] = {
    "default": {
        "width": 280,
        "alpha": 0.95,
        "bg":        "#0A0E14",
        "panel":     "#0F1419",
        "border":    "#1F2630",
        "text":      "#E6EDF3",
        "muted":     "#8B98A6",
        "good":      "#3FB68B",
        "warn":      "#E8A23B",
        "bad":       "#E5484D",
        "accent":    "#4A9EFF",
        "font":       ("Segoe UI", 10),
        "font_small": ("Segoe UI", 9),
        "font_mono":  ("Consolas", 9),
        "font_title": ("Segoe UI Semibold", 10),
        "pad":        12,
        "bar_h":       6,
        "gap":        10,
        "title_h":    28,
        "warn_at":    50,
        "bad_at":     80,
    },
    "neon": {
        "width": 280,
        "alpha": 0.95,
        "bg":        "#0D0D1A",
        "panel":     "#12122A",
        "border":    "#2D2D5E",
        "text":      "#E0E0FF",
        "muted":     "#7070AA",
        "good":      "#00FFD0",
        "warn":      "#FFD700",
        "bad":       "#FF2D78",
        "accent":    "#BD00FF",
        "font":       ("Segoe UI", 10),
        "font_small": ("Segoe UI", 9),
        "font_mono":  ("Consolas", 9),
        "font_title": ("Segoe UI Semibold", 10),
        "pad":        12,
        "bar_h":       6,
        "gap":        10,
        "title_h":    28,
        "warn_at":    50,
        "bad_at":     80,
    },
    "light": {
        "width": 280,
        "alpha": 0.97,
        "bg":        "#FFFFFF",
        "panel":     "#F5F5F5",
        "border":    "#E0E0E0",
        "text":      "#1A1A1A",
        "muted":     "#6B7280",
        "good":      "#16A34A",
        "warn":      "#D97706",
        "bad":       "#DC2626",
        "accent":    "#2563EB",
        "font":       ("Segoe UI", 10),
        "font_small": ("Segoe UI", 9),
        "font_mono":  ("Consolas", 9),
        "font_title": ("Segoe UI Semibold", 10),
        "pad":        12,
        "bar_h":       6,
        "gap":        10,
        "title_h":    28,
        "warn_at":    50,
        "bad_at":     80,
    },
    "minimal": {
        "width": 220,
        "alpha": 0.90,
        "bg":        "#111111",
        "panel":     "#111111",
        "border":    "#333333",
        "text":      "#CCCCCC",
        "muted":     "#555555",
        "good":      "#4CAF50",
        "warn":      "#FF9800",
        "bad":       "#F44336",
        "accent":    "#888888",
        "font":       ("Segoe UI", 9),
        "font_small": ("Segoe UI", 8),
        "font_mono":  ("Consolas", 9),
        "font_title": ("Segoe UI", 9),
        "pad":        8,
        "bar_h":       4,
        "gap":        8,
        "title_h":    24,
        "warn_at":    50,
        "bad_at":     80,
    },
}

THEME_NAMES: list[str] = list(_THEMES.keys())


def get_theme(name: str) -> dict:
    """Return a copy of the named theme, falling back to 'default'."""
    return dict(_THEMES.get(name, _THEMES["default"]))
